/*
 *  KCemu -- the KC 85/3 and KC 85/4 Emulator
 *  Copyright (C) 1997-1998 Torsten Paul
 *
 *  $Id: op.h,v 1.2 1998/10/28 23:47:02 tp Exp $
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef __op_h
#define __op_h

static opcodes_t opcodes[256] = {
	/* 0x00 */
	{"NOP",		_none,		_none},
	{"LD",		_r_BC,		_i_nn},
	{"LD",		_p_BC,		_r_A},
	{"INC",		_r_BC,		_none},
	{"INC",		_r_B,		_none},
	{"DEC",		_r_B,		_none},
	{"LD",		_r_B,		_i_n},
	{"RLCA",	_none,		_none},
	{"EXAF",	_none,		_none},
	{"ADD",		_r_HL,		_r_BC},
	{"LD",		_r_A,		_p_BC},
	{"DEC",		_r_BC,		_none},
	{"INC",		_r_C,		_none},
	{"DEC",		_r_C,		_none},
	{"LD",		_r_C,		_i_n},
	{"RRCA",	_none,		_none},
	/* 0x10 */
	{"DJNZ",	_i_e,		_none},
	{"LD",		_r_DE,		_i_nn},
	{"LD",		_p_DE,		_r_A},
	{"INC",		_r_DE,		_none},
	{"INC",		_r_D,		_none},
	{"DEC",		_r_D,		_none},
	{"LD",		_r_D,		_i_n},
	{"RLA",		_none,		_none},
	{"JR",		_i_e,		_none},
	{"ADD",		_r_HL,		_r_DE},
	{"LD",		_r_A,		_p_DE},
	{"DEC",		_r_DE,		_none},
	{"INC",		_r_E,		_none},
	{"DEC",		_r_E,		_none},
	{"LD",		_r_E,		_i_n},
	{"RRA",		_none,		_none},
	/* 0x20 */
	{"JR,NZ",	_i_e,		_none},
	{"LD",		_r_HL,		_i_nn},
	{"LD",		_p_nn,		_r_HL},
	{"INC",		_r_HL,		_none},
	{"INC",		_r_H,		_none},
	{"DEC",		_r_H,		_none},
	{"LD",		_r_H,		_i_n},
	{"DAA",		_none,		_none},
	{"JR,Z",	_i_e,		_none},
	{"ADD",		_r_HL,		_r_HL},
	{"LD",		_r_HL,		_p_nn},
	{"DEC",		_r_HL,		_none},
	{"INC",		_r_L,		_none},
	{"DEC",		_r_L,		_none},
	{"LD",		_r_L,		_i_n},
	{"CPL",		_none,		_none},
	/* 0x30 */
	{"JR,NC",	_i_e,		_none},
	{"LD",		_r_SP,		_i_nn},
	{"LD",		_p_nn,		_r_A},
	{"INC",		_r_SP,		_none},
	{"INC",		_p_HL,		_none},
	{"DEC",		_p_HL,		_none},
	{"LD",		_p_HL,		_i_n},
	{"SCF",		_none,		_none},
	{"JR,C",	_i_e,		_none},
	{"ADD",		_r_HL,		_r_SP},
	{"LD",		_r_A,		_p_nn},
	{"DEC",		_r_SP,		_none},
	{"INC",		_r_A,		_none},
	{"DEC",		_r_A,		_none},
	{"LD",		_r_A,		_i_n},
	{"CCF",		_none,		_none},
	/* 0x40 */
	{"LD",		_r_B,		_r_B},
	{"LD",		_r_B,		_r_C},
	{"LD",		_r_B,		_r_D},
	{"LD",		_r_B,		_r_E},
	{"LD",		_r_B,		_r_H},
	{"LD",		_r_B,		_r_L},
	{"LD",		_r_B,		_p_HL},
	{"LD",		_r_B,		_r_A},
	{"LD",		_r_C,		_r_B},
	{"LD",		_r_C,		_r_C},
	{"LD",		_r_C,		_r_D},
	{"LD",		_r_C,		_r_E},
	{"LD",		_r_C,		_r_H},
	{"LD",		_r_C,		_r_L},
	{"LD",		_r_C,		_p_HL},
	{"LD",		_r_C,		_r_A},
	/* 0x50 */
	{"LD",		_r_D,		_r_B},
	{"LD",		_r_D,		_r_C},
	{"LD",		_r_D,		_r_D},
	{"LD",		_r_D,		_r_E},
	{"LD",		_r_D,		_r_H},
	{"LD",		_r_D,		_r_L},
	{"LD",		_r_D,		_p_HL},
	{"LD",		_r_D,		_r_A},
	{"LD",		_r_E,		_r_B},
	{"LD",		_r_E,		_r_C},
	{"LD",		_r_E,		_r_D},
	{"LD",		_r_E,		_r_E},
	{"LD",		_r_E,		_r_H},
	{"LD",		_r_E,		_r_L},
	{"LD",		_r_E,		_p_HL},
	{"LD",		_r_E,		_r_A},
	/* 0x60 */
	{"LD",		_r_H,		_r_B},
	{"LD",		_r_H,		_r_C},
	{"LD",		_r_H,		_r_D},
	{"LD",		_r_H,		_r_E},
	{"LD",		_r_H,		_r_H},
	{"LD",		_r_H,		_r_L},
	{"LD",		_r_H,		_p_HL},
	{"LD",		_r_H,		_r_A},
	{"LD",		_r_L,		_r_B},
	{"LD",		_r_L,		_r_C},
	{"LD",		_r_L,		_r_D},
	{"LD",		_r_L,		_r_E},
	{"LD",		_r_L,		_r_H},
	{"LD",		_r_L,		_r_L},
	{"LD",		_r_L,		_p_HL},
	{"LD",		_r_L,		_r_A},
	/* 0x70 */
	{"LD",		_p_HL,		_r_B},
	{"LD",		_p_HL,		_r_C},
	{"LD",		_p_HL,		_r_D},
	{"LD",		_p_HL,		_r_E},
	{"LD",		_p_HL,		_r_H},
	{"LD",		_p_HL,		_r_L},
	{"HALT",	_none,		_none},
	{"LD",		_p_HL,		_r_A},
	{"LD",		_r_A,		_r_B},
	{"LD",		_r_A,		_r_C},
	{"LD",		_r_A,		_r_D},
	{"LD",		_r_A,		_r_E},
	{"LD",		_r_A,		_r_H},
	{"LD",		_r_A,		_r_L},
	{"LD",		_r_A,		_p_HL},
	{"LD",		_r_A,		_r_A},
	/* 0x80 */
	{"ADD",		_r_A,		_r_B},
	{"ADD",		_r_A,		_r_C},
	{"ADD",		_r_A,		_r_D},
	{"ADD",		_r_A,		_r_E},
	{"ADD",		_r_A,		_r_H},
	{"ADD",		_r_A,		_r_L},
	{"ADD",		_r_A,		_p_HL},
	{"ADD",		_r_A,		_r_A},
	{"ADC",		_r_A,		_r_B},
	{"ADC",		_r_A,		_r_C},
	{"ADC",		_r_A,		_r_D},
	{"ADC",		_r_A,		_r_E},
	{"ADC",		_r_A,		_r_H},
	{"ADC",		_r_A,		_r_L},
	{"ADC",		_r_A,		_p_HL},
	{"ADC",		_r_A,		_r_A},
	/* 0x90 */
	{"SUB",		_r_A,		_r_B},
	{"SUB",		_r_A,		_r_C},
	{"SUB",		_r_A,		_r_D},
	{"SUB",		_r_A,		_r_E},
	{"SUB",		_r_A,		_r_H},
	{"SUB",		_r_A,		_r_L},
	{"SUB",		_r_A,		_p_HL},
	{"SUB",		_r_A,		_r_A},
	{"SBC",		_r_A,		_r_B},
	{"SBC",		_r_A,		_r_C},
	{"SBC",		_r_A,		_r_D},
	{"SBC",		_r_A,		_r_E},
	{"SBC",		_r_A,		_r_H},
	{"SBC",		_r_A,		_r_L},
	{"SBC",		_r_A,		_p_HL},
	{"SBC",		_r_A,		_r_A},
	/* 0xa0 */
	{"AND",		_r_A,		_r_B},
	{"AND",		_r_A,		_r_C},
	{"AND",		_r_A,		_r_D},
	{"AND",		_r_A,		_r_E},
	{"AND",		_r_A,		_r_H},
	{"AND",		_r_A,		_r_L},
	{"AND",		_r_A,		_p_HL},
	{"AND",		_r_A,		_r_A},
	{"XOR",		_r_A,		_r_B},
	{"XOR",		_r_A,		_r_C},
	{"XOR",		_r_A,		_r_D},
	{"XOR",		_r_A,		_r_E},
	{"XOR",		_r_A,		_r_H},
	{"XOR",		_r_A,		_r_L},
	{"XOR",		_r_A,		_p_HL},
	{"XOR",		_r_A,		_r_A},
	/* 0xb0 */
	{"OR",		_r_A,		_r_B},
	{"OR",		_r_A,		_r_C},
	{"OR",		_r_A,		_r_D},
	{"OR",		_r_A,		_r_E},
	{"OR",		_r_A,		_r_H},
	{"OR",		_r_A,		_r_L},
	{"OR",		_r_A,		_p_HL},
	{"OR",		_r_A,		_r_A},
	{"CP",		_r_A,		_r_B},
	{"CP",		_r_A,		_r_C},
	{"CP",		_r_A,		_r_D},
	{"CP",		_r_A,		_r_E},
	{"CP",		_r_A,		_r_H},
	{"CP",		_r_A,		_r_L},
	{"CP",		_r_A,		_p_HL},
	{"CP",		_r_A,		_r_A},
	/* 0xc0 */
	{"RET,NZ",	_none,		_none},
	{"POP",		_r_BC,		_none},
	{"JP,NZ",	_i_nn,		_none},
	{"JP",		_i_nn,		_none},
	{"CALL,NZ",	_i_nn,		_none},
	{"PUSH",	_r_BC,		_none},
	{"ADD",		_r_A,		_i_n},
	{"RST",		_x_00h,		_none},
	{"RET,Z",	_none,		_none},
	{"RET",		_none,		_none},
	{"JP,Z",	_i_nn,		_none},
	{"#",		_none,		_none}, /* 0xcb: code page prefix */
	{"CALL,Z",	_i_nn,		_none},
	{"CALL",	_i_nn,		_none},
	{"ADC",		_r_A,		_i_n},
	{"RST",		_x_08h,		_none},
	/* 0xd0 */
	{"RET,NC",	_none,		_none},
	{"POP",		_r_DE,		_none},
	{"JP,NC",	_i_nn,		_none},
	{"OUT",		_i_n,		_none},
	{"CALL,NC",	_i_nn,		_none},
	{"PUSH",	_r_DE,		_none},
	{"SUB",		_r_A,		_i_n},
	{"RST",		_x_10h,		_none},
	{"RET,C",	_none,		_none},
	{"EXX",		_none,		_none},
	{"JP,C",	_i_nn,		_none},
	{"IN",		_i_n,		_none},
	{"CALL,C",	_i_nn,		_none},
	{"#",		_none,		_none}, /* 0xdd: code page prefix */
	{"SBC",		_r_A,		_i_n},
	{"RST",		_x_18h,		_none},
	/* 0xe0 */
	{"RET,PO",	_none,		_none},
	{"POP",		_r_HL,		_none},
	{"JP,PO",	_i_nn,		_none},
	{"EX",		_p_SP,		_r_HL},
	{"CALL,PO",	_i_nn,		_none},
	{"PUSH",	_r_HL,		_none},
	{"AND",		_r_A,		_i_n},
	{"RST",		_x_20h,		_none},
	{"RET,PE",	_none,		_none},
	{"JP",		_p_HL,		_none},
	{"JP,PE",	_i_nn,		_none},
	{"EX",		_r_DE,		_r_HL},
	{"CALL,PE",	_i_nn,		_none},
	{"#",		_none,		_none}, /* 0xed: code page prefix */
	{"XOR",		_r_A,		_i_n},
	{"RST",		_x_28h,		_none},
	/* 0xf0 */
	{"RET,P",	_none,		_none},
	{"POP",		_r_AF,		_none},
	{"JP,P",	_i_nn,		_none},
	{"DI",		_none,		_none},
	{"CALL,P",	_i_nn,		_none},
	{"PUSH",	_r_AF,		_none},
	{"OR",		_r_A,		_i_n},
	{"RST",		_x_30h,		_none},
	{"RET,M",	_none,		_none},
	{"LD",		_p_SP,		_r_HL},
	{"JP,M",	_i_nn,		_none},
	{"EI",		_none,		_none},
	{"CALL,M",	_i_nn,		_none},
	{"#",		_none,		_none}, /* 0xfd: code page prefix */
	{"CP",		_r_A,		_i_n},
	{"RST",		_x_38h,		_none}
};

#endif /* __op_h */
