
#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef USE_INCLUDED_LIBINTL
#undef HAVE_STPCPY

#undef KCEMU_MAJOR_VERSION
#undef KCEMU_MICRO_VERSION
#undef KCEMU_MINOR_VERSION
#undef KCEMU_EXTRA_VERSION
#undef KCEMU_VERSION

#undef DBG_LEVEL

#undef HOST_OS
#undef HOST_OS_BEOS
#undef HOST_OS_LINUX

#undef HAVE_GETOPT
#undef HAVE_GETOPT_LONG

#undef HAVE_LIBSDL
#undef HAVE_LIBGTK
#undef HAVE_LIBSNDFILE
#undef HAVE_LIBSNDFILE_V0
#undef HAVE_LIBSNDFILE_V1

#undef HAVE_LIBAUDIOFILE
#undef HAVE_LIBVORBIS
#undef HAVE_LIBMP3LAME
#undef HAVE_LIBFLAC

#undef USE_UI_GTK
#undef USE_UI_SDL

#undef ENABLE_SOUND

/* #undef PACKAGE */
/* #undef VERSION */

