/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "about_callback.h"
#include "about_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_about_window (void)
{
  GtkWidget *about_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *main_vbox;
  GtkWidget *main_image;
  GtkWidget *main_label_version;
  GtkWidget *main_label_copyright;
  GtkWidget *main_label_mail;
  GtkWidget *main_label_build;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_close;

  about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (about_window, "about_window");
  gtk_window_set_title (GTK_WINDOW (about_window), _("KCemu: About"));
  gtk_window_set_position (GTK_WINDOW (about_window), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (about_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (about_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("About"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 6);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);

  header_image = create_pixmap (about_window, "window-about.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_box_pack_start (GTK_BOX (vbox), main_vbox, TRUE, TRUE, 0);

  main_image = create_pixmap (about_window, "kcemu.png");
  gtk_widget_set_name (main_image, "main_image");
  gtk_widget_show (main_image);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_image, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (main_image), 20, 6);

  main_label_version = gtk_label_new (_("[ Version ]"));
  gtk_widget_set_name (main_label_version, "main_label_version");
  gtk_widget_show (main_label_version);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_version, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_version, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_version), TRUE);
  gtk_misc_set_padding (GTK_MISC (main_label_version), 0, 8);

  main_label_copyright = gtk_label_new (_("(c) 1997-2006 Torsten Paul"));
  gtk_widget_set_name (main_label_copyright, "main_label_copyright");
  gtk_widget_show (main_label_copyright);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_copyright, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_copyright, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_copyright), TRUE);

  main_label_mail = gtk_label_new (_("<Torsten.Paul@gmx.de>"));
  gtk_widget_set_name (main_label_mail, "main_label_mail");
  gtk_widget_show (main_label_mail);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_mail, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_mail, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_mail), TRUE);

  main_label_build = gtk_label_new (_("[ Build ]"));
  gtk_widget_set_name (main_label_build, "main_label_build");
  gtk_widget_show (main_label_build);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_build, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_build, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_build), TRUE);
  gtk_misc_set_padding (GTK_MISC (main_label_build), 0, 8);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, TRUE, 6);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_hbuttonbox), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_window, about_window, "about_window");
  GLADE_HOOKUP_OBJECT (about_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (about_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (about_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (about_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (about_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (about_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (about_window, main_image, "main_image");
  GLADE_HOOKUP_OBJECT (about_window, main_label_version, "main_label_version");
  GLADE_HOOKUP_OBJECT (about_window, main_label_copyright, "main_label_copyright");
  GLADE_HOOKUP_OBJECT (about_window, main_label_mail, "main_label_mail");
  GLADE_HOOKUP_OBJECT (about_window, main_label_build, "main_label_build");
  GLADE_HOOKUP_OBJECT (about_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (about_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (about_window, dialog_button_close, "dialog_button_close");

  gtk_widget_grab_focus (dialog_button_close);
  gtk_widget_grab_default (dialog_button_close);
  return about_window;
}

