/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "copying_callback.h"
#include "copying_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_copying_window (void)
{
  GtkWidget *copying_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *image;
  GtkWidget *main_scrolledwindow;
  GtkWidget *main_viewport;
  GtkWidget *main_vbox;
  GtkWidget *main_label_license;
  GtkWidget *main_label_warranty;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_close;

  copying_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (copying_window, "copying_window");
  gtk_window_set_title (GTK_WINDOW (copying_window), _("KCemu: Licence & Warranty"));
  gtk_window_set_position (GTK_WINDOW (copying_window), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (copying_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (copying_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("License & Warranty"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (header_label), 6, 0);

  header_image = create_pixmap (copying_window, "window-copying.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, FALSE, 6);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  image = create_pixmap (copying_window, "kcemu.png");
  gtk_widget_set_name (image, "image");
  gtk_widget_show (image);
  gtk_box_pack_start (GTK_BOX (vbox), image, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image), 20, 8);

  main_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scrolledwindow, "main_scrolledwindow");
  gtk_widget_show (main_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (vbox), main_scrolledwindow, TRUE, TRUE, 6);
  gtk_widget_set_size_request (main_scrolledwindow, 660, 300);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  main_viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (main_viewport, "main_viewport");
  gtk_widget_show (main_viewport);
  gtk_container_add (GTK_CONTAINER (main_scrolledwindow), main_viewport);

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_container_add (GTK_CONTAINER (main_viewport), main_vbox);

  main_label_license = gtk_label_new (_("[ Licence ]"));
  gtk_widget_set_name (main_label_license, "main_label_license");
  gtk_widget_show (main_label_license);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_license, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_license, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_license), TRUE);

  main_label_warranty = gtk_label_new (_("[ Warranty ]"));
  gtk_widget_set_name (main_label_warranty, "main_label_warranty");
  gtk_widget_show (main_label_warranty);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_label_warranty, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (main_label_warranty, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (main_label_warranty), TRUE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, TRUE, 0);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_hbuttonbox), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (copying_window, copying_window, "copying_window");
  GLADE_HOOKUP_OBJECT (copying_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (copying_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (copying_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (copying_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (copying_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (copying_window, image, "image");
  GLADE_HOOKUP_OBJECT (copying_window, main_scrolledwindow, "main_scrolledwindow");
  GLADE_HOOKUP_OBJECT (copying_window, main_viewport, "main_viewport");
  GLADE_HOOKUP_OBJECT (copying_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (copying_window, main_label_license, "main_label_license");
  GLADE_HOOKUP_OBJECT (copying_window, main_label_warranty, "main_label_warranty");
  GLADE_HOOKUP_OBJECT (copying_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (copying_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (copying_window, dialog_button_close, "dialog_button_close");

  gtk_widget_grab_focus (dialog_button_close);
  gtk_widget_grab_default (dialog_button_close);
  return copying_window;
}

