/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "dialog_callback.h"
#include "dialog_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog_window (void)
{
  GtkWidget *dialog_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_label_separator;
  GtkWidget *header_image_question;
  GtkWidget *header_image_info;
  GtkWidget *main_scrolledwindow;
  GtkWidget *main_textview;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_yes;
  GtkWidget *dialog_button_no;
  GtkWidget *dialog_button_ok;

  dialog_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dialog_window, "dialog_window");
  gtk_window_set_title (GTK_WINDOW (dialog_window), _("KCemu"));
  gtk_window_set_position (GTK_WINDOW (dialog_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dialog_window), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (dialog_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("[ Title ]"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (header_label), 4, 0);

  header_label_separator = gtk_label_new ("");
  gtk_widget_set_name (header_label_separator, "header_label_separator");
  gtk_widget_show (header_label_separator);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label_separator, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (header_label_separator), 16, 0);

  header_image_question = create_pixmap (dialog_window, "window-question.png");
  gtk_widget_set_name (header_image_question, "header_image_question");
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image_question, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image_question), 4, 4);

  header_image_info = create_pixmap (dialog_window, "window-info.png");
  gtk_widget_set_name (header_image_info, "header_image_info");
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image_info, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image_info), 4, 4);

  main_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scrolledwindow, "main_scrolledwindow");
  gtk_widget_show (main_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (vbox), main_scrolledwindow, TRUE, TRUE, 2);
  gtk_widget_set_size_request (main_scrolledwindow, 400, -1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_SHADOW_IN);

  main_textview = gtk_text_view_new ();
  gtk_widget_set_name (main_textview, "main_textview");
  gtk_widget_show (main_textview);
  gtk_container_add (GTK_CONTAINER (main_scrolledwindow), main_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (main_textview), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (main_textview), FALSE);
  gtk_text_view_set_pixels_above_lines (GTK_TEXT_VIEW (main_textview), 2);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (main_textview), 4);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, TRUE, 6);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_hbuttonbox), 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (dialog_hbuttonbox), 4);

  dialog_button_yes = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_set_name (dialog_button_yes, "dialog_button_yes");
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_yes);
  GTK_WIDGET_SET_FLAGS (dialog_button_yes, GTK_CAN_DEFAULT);

  dialog_button_no = gtk_button_new_from_stock ("gtk-no");
  gtk_widget_set_name (dialog_button_no, "dialog_button_no");
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_no);
  GTK_WIDGET_SET_FLAGS (dialog_button_no, GTK_CAN_DEFAULT);

  dialog_button_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (dialog_button_ok, "dialog_button_ok");
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_ok);
  GTK_WIDGET_SET_FLAGS (dialog_button_ok, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_window, dialog_window, "dialog_window");
  GLADE_HOOKUP_OBJECT (dialog_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (dialog_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (dialog_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (dialog_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (dialog_window, header_label_separator, "header_label_separator");
  GLADE_HOOKUP_OBJECT (dialog_window, header_image_question, "header_image_question");
  GLADE_HOOKUP_OBJECT (dialog_window, header_image_info, "header_image_info");
  GLADE_HOOKUP_OBJECT (dialog_window, main_scrolledwindow, "main_scrolledwindow");
  GLADE_HOOKUP_OBJECT (dialog_window, main_textview, "main_textview");
  GLADE_HOOKUP_OBJECT (dialog_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (dialog_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (dialog_window, dialog_button_yes, "dialog_button_yes");
  GLADE_HOOKUP_OBJECT (dialog_window, dialog_button_no, "dialog_button_no");
  GLADE_HOOKUP_OBJECT (dialog_window, dialog_button_ok, "dialog_button_ok");

  return dialog_window;
}

