/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "disk_callback.h"
#include "disk_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_disk_window (void)
{
  GtkWidget *disk_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *main_table;
  GtkWidget *disk_label_1;
  GtkWidget *disk_label_2;
  GtkWidget *disk_label_3;
  GtkWidget *disk_label_4;
  GtkWidget *disk_comboboxentry_1;
  GtkWidget *disk_comboboxentry_2;
  GtkWidget *disk_comboboxentry_4;
  GtkWidget *disk_button_open_1;
  GtkWidget *image1;
  GtkWidget *disk_button_open_2;
  GtkWidget *image3;
  GtkWidget *disk_button_open_3;
  GtkWidget *image4;
  GtkWidget *disk_button_open_4;
  GtkWidget *image2;
  GtkWidget *disk_button_close_1;
  GtkWidget *image16;
  GtkWidget *disk_button_close_2;
  GtkWidget *image17;
  GtkWidget *disk_button_close_3;
  GtkWidget *image18;
  GtkWidget *disk_button_close_4;
  GtkWidget *image19;
  GtkWidget *disk_comboboxentry_3;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_help;
  GtkWidget *dialog_button_close;

  disk_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (disk_window, "disk_window");
  gtk_window_set_title (GTK_WINDOW (disk_window), _("KCemu: Disk"));
  gtk_window_set_position (GTK_WINDOW (disk_window), GTK_WIN_POS_MOUSE);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (disk_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (header_frame), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("Disk"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (header_label), 6, 0);

  header_image = create_pixmap (disk_window, "window-disk.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  main_table = gtk_table_new (4, 4, FALSE);
  gtk_widget_set_name (main_table, "main_table");
  gtk_widget_show (main_table);
  gtk_box_pack_start (GTK_BOX (vbox), main_table, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (main_table), 4);
  gtk_table_set_row_spacings (GTK_TABLE (main_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (main_table), 2);

  disk_label_1 = gtk_label_new (_("Disk 1:"));
  gtk_widget_set_name (disk_label_1, "disk_label_1");
  gtk_widget_show (disk_label_1);
  gtk_table_attach (GTK_TABLE (main_table), disk_label_1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (disk_label_1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (disk_label_1), 4, 0);

  disk_label_2 = gtk_label_new (_("Disk 2:"));
  gtk_widget_set_name (disk_label_2, "disk_label_2");
  gtk_widget_show (disk_label_2);
  gtk_table_attach (GTK_TABLE (main_table), disk_label_2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (disk_label_2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (disk_label_2), 4, 0);

  disk_label_3 = gtk_label_new (_("Disk 3:"));
  gtk_widget_set_name (disk_label_3, "disk_label_3");
  gtk_widget_show (disk_label_3);
  gtk_table_attach (GTK_TABLE (main_table), disk_label_3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (disk_label_3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (disk_label_3), 4, 0);

  disk_label_4 = gtk_label_new (_("Disk 4:"));
  gtk_widget_set_name (disk_label_4, "disk_label_4");
  gtk_widget_show (disk_label_4);
  gtk_table_attach (GTK_TABLE (main_table), disk_label_4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (disk_label_4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (disk_label_4), 4, 0);

  disk_comboboxentry_1 = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (disk_comboboxentry_1, "disk_comboboxentry_1");
  gtk_widget_show (disk_comboboxentry_1);
  gtk_table_attach (GTK_TABLE (main_table), disk_comboboxentry_1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "microdos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "caos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "tools.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "a5105sys.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "cpmz9.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "z1013cpm.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_1), "z1013gdc.dump");

  disk_comboboxentry_2 = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (disk_comboboxentry_2, "disk_comboboxentry_2");
  gtk_widget_show (disk_comboboxentry_2);
  gtk_table_attach (GTK_TABLE (main_table), disk_comboboxentry_2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "microdos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "caos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "tools.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "a5105sys.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "cpmz9.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "z1013cpm.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_2), "z1013gdc.dump");

  disk_comboboxentry_4 = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (disk_comboboxentry_4, "disk_comboboxentry_4");
  gtk_widget_show (disk_comboboxentry_4);
  gtk_table_attach (GTK_TABLE (main_table), disk_comboboxentry_4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "microdos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "caos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "tools.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "a5105sys.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "cpmz9.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "z1013cpm.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_4), "z1013gdc.dump");

  disk_button_open_1 = gtk_button_new ();
  gtk_widget_set_name (disk_button_open_1, "disk_button_open_1");
  gtk_widget_show (disk_button_open_1);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_open_1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image1 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (disk_button_open_1), image1);

  disk_button_open_2 = gtk_button_new ();
  gtk_widget_set_name (disk_button_open_2, "disk_button_open_2");
  gtk_widget_show (disk_button_open_2);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_open_2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image3 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image3, "image3");
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (disk_button_open_2), image3);

  disk_button_open_3 = gtk_button_new ();
  gtk_widget_set_name (disk_button_open_3, "disk_button_open_3");
  gtk_widget_show (disk_button_open_3);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_open_3, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image4 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (disk_button_open_3), image4);

  disk_button_open_4 = gtk_button_new ();
  gtk_widget_set_name (disk_button_open_4, "disk_button_open_4");
  gtk_widget_show (disk_button_open_4);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_open_4, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image2 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (disk_button_open_4), image2);

  disk_button_close_1 = gtk_button_new ();
  gtk_widget_set_name (disk_button_close_1, "disk_button_close_1");
  gtk_widget_show (disk_button_close_1);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_close_1, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image16 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image16, "image16");
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (disk_button_close_1), image16);

  disk_button_close_2 = gtk_button_new ();
  gtk_widget_set_name (disk_button_close_2, "disk_button_close_2");
  gtk_widget_show (disk_button_close_2);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_close_2, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image17 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image17, "image17");
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (disk_button_close_2), image17);

  disk_button_close_3 = gtk_button_new ();
  gtk_widget_set_name (disk_button_close_3, "disk_button_close_3");
  gtk_widget_show (disk_button_close_3);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_close_3, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image18 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image18, "image18");
  gtk_widget_show (image18);
  gtk_container_add (GTK_CONTAINER (disk_button_close_3), image18);

  disk_button_close_4 = gtk_button_new ();
  gtk_widget_set_name (disk_button_close_4, "disk_button_close_4");
  gtk_widget_show (disk_button_close_4);
  gtk_table_attach (GTK_TABLE (main_table), disk_button_close_4, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image19 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image19, "image19");
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (disk_button_close_4), image19);

  disk_comboboxentry_3 = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (disk_comboboxentry_3, "disk_comboboxentry_3");
  gtk_widget_show (disk_comboboxentry_3);
  gtk_table_attach (GTK_TABLE (main_table), disk_comboboxentry_3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "microdos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "caos.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "tools.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "a5105sys.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "cpmz9.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "z1013cpm.dump");
  gtk_combo_box_append_text (GTK_COMBO_BOX (disk_comboboxentry_3), "z1013gdc.dump");

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, FALSE, 4);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_hbuttonbox), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (dialog_hbuttonbox), 6);

  dialog_button_help = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_set_name (dialog_button_help, "dialog_button_help");
  gtk_widget_show (dialog_button_help);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_help);
  GTK_WIDGET_SET_FLAGS (dialog_button_help, GTK_CAN_DEFAULT);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (disk_window, disk_window, "disk_window");
  GLADE_HOOKUP_OBJECT (disk_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (disk_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (disk_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (disk_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (disk_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (disk_window, main_table, "main_table");
  GLADE_HOOKUP_OBJECT (disk_window, disk_label_1, "disk_label_1");
  GLADE_HOOKUP_OBJECT (disk_window, disk_label_2, "disk_label_2");
  GLADE_HOOKUP_OBJECT (disk_window, disk_label_3, "disk_label_3");
  GLADE_HOOKUP_OBJECT (disk_window, disk_label_4, "disk_label_4");
  GLADE_HOOKUP_OBJECT (disk_window, disk_comboboxentry_1, "disk_comboboxentry_1");
  GLADE_HOOKUP_OBJECT (disk_window, disk_comboboxentry_2, "disk_comboboxentry_2");
  GLADE_HOOKUP_OBJECT (disk_window, disk_comboboxentry_4, "disk_comboboxentry_4");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_open_1, "disk_button_open_1");
  GLADE_HOOKUP_OBJECT (disk_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_open_2, "disk_button_open_2");
  GLADE_HOOKUP_OBJECT (disk_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_open_3, "disk_button_open_3");
  GLADE_HOOKUP_OBJECT (disk_window, image4, "image4");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_open_4, "disk_button_open_4");
  GLADE_HOOKUP_OBJECT (disk_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_close_1, "disk_button_close_1");
  GLADE_HOOKUP_OBJECT (disk_window, image16, "image16");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_close_2, "disk_button_close_2");
  GLADE_HOOKUP_OBJECT (disk_window, image17, "image17");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_close_3, "disk_button_close_3");
  GLADE_HOOKUP_OBJECT (disk_window, image18, "image18");
  GLADE_HOOKUP_OBJECT (disk_window, disk_button_close_4, "disk_button_close_4");
  GLADE_HOOKUP_OBJECT (disk_window, image19, "image19");
  GLADE_HOOKUP_OBJECT (disk_window, disk_comboboxentry_3, "disk_comboboxentry_3");
  GLADE_HOOKUP_OBJECT (disk_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (disk_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (disk_window, dialog_button_help, "dialog_button_help");
  GLADE_HOOKUP_OBJECT (disk_window, dialog_button_close, "dialog_button_close");

  return disk_window;
}

