/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "help_callback.h"
#include "help_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_help_window (void)
{
  GtkWidget *help_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *main_vbox;
  GtkWidget *hbuttonbox1;
  GtkWidget *navigation_button_back;
  GtkWidget *navigation_button_forward;
  GtkWidget *navigation_button_home;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *navigation_button_index;
  GtkWidget *navigation_button_refresh;
  GtkWidget *main_scrolledwindow;
  GtkWidget *main_textview;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_close;

  help_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (help_window, "help_window");
  gtk_window_set_title (GTK_WINDOW (help_window), _("KCemu: Help"));
  gtk_window_set_position (GTK_WINDOW (help_window), GTK_WIN_POS_MOUSE);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (help_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("Help"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (header_label), 6, 0);

  header_image = create_pixmap (help_window, "window-help.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_box_pack_start (GTK_BOX (vbox), main_vbox, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (main_vbox), hbuttonbox1, FALSE, FALSE, 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_START);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 4);

  navigation_button_back = gtk_button_new_from_stock ("gtk-go-back");
  gtk_widget_set_name (navigation_button_back, "navigation_button_back");
  gtk_widget_show (navigation_button_back);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), navigation_button_back);
  gtk_widget_set_sensitive (navigation_button_back, FALSE);
  GTK_WIDGET_SET_FLAGS (navigation_button_back, GTK_CAN_DEFAULT);

  navigation_button_forward = gtk_button_new_from_stock ("gtk-go-forward");
  gtk_widget_set_name (navigation_button_forward, "navigation_button_forward");
  gtk_widget_show (navigation_button_forward);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), navigation_button_forward);
  gtk_widget_set_sensitive (navigation_button_forward, FALSE);
  GTK_WIDGET_SET_FLAGS (navigation_button_forward, GTK_CAN_DEFAULT);

  navigation_button_home = gtk_button_new ();
  gtk_widget_set_name (navigation_button_home, "navigation_button_home");
  gtk_widget_show (navigation_button_home);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), navigation_button_home);
  GTK_WIDGET_SET_FLAGS (navigation_button_home, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (navigation_button_home), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic ("Home");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  navigation_button_index = gtk_button_new_from_stock ("gtk-index");
  gtk_widget_set_name (navigation_button_index, "navigation_button_index");
  gtk_widget_show (navigation_button_index);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), navigation_button_index);
  GTK_WIDGET_SET_FLAGS (navigation_button_index, GTK_CAN_DEFAULT);

  navigation_button_refresh = gtk_button_new_from_stock ("gtk-refresh");
  gtk_widget_set_name (navigation_button_refresh, "navigation_button_refresh");
  gtk_widget_show (navigation_button_refresh);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), navigation_button_refresh);
  GTK_WIDGET_SET_FLAGS (navigation_button_refresh, GTK_CAN_DEFAULT);

  main_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scrolledwindow, "main_scrolledwindow");
  gtk_widget_show (main_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_scrolledwindow, TRUE, TRUE, 0);
  gtk_widget_set_size_request (main_scrolledwindow, 600, 300);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_SHADOW_IN);

  main_textview = gtk_text_view_new ();
  gtk_widget_set_name (main_textview, "main_textview");
  gtk_widget_show (main_textview);
  gtk_container_add (GTK_CONTAINER (main_scrolledwindow), main_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (main_textview), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (main_textview), FALSE);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (main_textview), 4);
  gtk_text_view_set_right_margin (GTK_TEXT_VIEW (main_textview), 4);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, TRUE, 6);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_hbuttonbox), 6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (help_window, help_window, "help_window");
  GLADE_HOOKUP_OBJECT (help_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (help_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (help_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (help_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (help_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (help_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (help_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (help_window, navigation_button_back, "navigation_button_back");
  GLADE_HOOKUP_OBJECT (help_window, navigation_button_forward, "navigation_button_forward");
  GLADE_HOOKUP_OBJECT (help_window, navigation_button_home, "navigation_button_home");
  GLADE_HOOKUP_OBJECT (help_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (help_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (help_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (help_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (help_window, navigation_button_index, "navigation_button_index");
  GLADE_HOOKUP_OBJECT (help_window, navigation_button_refresh, "navigation_button_refresh");
  GLADE_HOOKUP_OBJECT (help_window, main_scrolledwindow, "main_scrolledwindow");
  GLADE_HOOKUP_OBJECT (help_window, main_textview, "main_textview");
  GLADE_HOOKUP_OBJECT (help_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (help_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (help_window, dialog_button_close, "dialog_button_close");

  gtk_widget_grab_focus (dialog_button_close);
  gtk_widget_grab_default (dialog_button_close);
  return help_window;
}

