/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "module_callback.h"
#include "module_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_module_window (void)
{
  GtkWidget *module_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *main_vbox;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_help;
  GtkWidget *dialog_button_close;

  module_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (module_window, "module_window");
  gtk_window_set_title (GTK_WINDOW (module_window), _("KCemu: Module"));
  gtk_window_set_position (GTK_WINDOW (module_window), GTK_WIN_POS_MOUSE);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (module_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("Module"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 6);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);

  header_image = create_pixmap (module_window, "window-module.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  main_vbox = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_box_pack_start (GTK_BOX (vbox), main_vbox, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (main_vbox), 2);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, TRUE, 4);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (dialog_hbuttonbox), 4);

  dialog_button_help = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_set_name (dialog_button_help, "dialog_button_help");
  gtk_widget_show (dialog_button_help);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_help);
  GTK_WIDGET_SET_FLAGS (dialog_button_help, GTK_CAN_DEFAULT);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (module_window, module_window, "module_window");
  GLADE_HOOKUP_OBJECT (module_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (module_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (module_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (module_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (module_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (module_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (module_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (module_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (module_window, dialog_button_help, "dialog_button_help");
  GLADE_HOOKUP_OBJECT (module_window, dialog_button_close, "dialog_button_close");

  return module_window;
}

