/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "tape_callback.h"
#include "tape_interface.h"
#include "glade_util.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_tape_window (void)
{
  GtkWidget *tape_window;
  GtkWidget *vbox;
  GtkWidget *header_frame;
  GtkWidget *header_hbox;
  GtkWidget *header_label;
  GtkWidget *header_image;
  GtkWidget *main_vbox;
  GtkWidget *file_hbox;
  GtkWidget *file_comboboxentry;
  GtkWidget *file_button_open;
  GtkWidget *file_button_image_open;
  GtkWidget *file_button_close;
  GtkWidget *file_button_image_close;
  GtkWidget *main_scrolledwindow;
  GtkWidget *main_treeview;
  GtkWidget *progress_hbox;
  GtkWidget *progress_led;
  GtkWidget *progress_hscale;
  GtkWidget *control_hbox;
  GtkWidget *control_button_play;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *control_button_previous;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *control_button_next;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *control_button_stop;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *control_button_record;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *hseparator1;
  GtkWidget *dialog_hbuttonbox;
  GtkWidget *dialog_button_help;
  GtkWidget *dialog_button_close;

  tape_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (tape_window, "tape_window");
  gtk_window_set_title (GTK_WINDOW (tape_window), _("KCemu: Tape"));
  gtk_window_set_position (GTK_WINDOW (tape_window), GTK_WIN_POS_MOUSE);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox, "vbox");
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (tape_window), vbox);

  header_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (header_frame, "header_frame");
  gtk_widget_show (header_frame);
  gtk_box_pack_start (GTK_BOX (vbox), header_frame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (header_frame), GTK_SHADOW_ETCHED_OUT);

  header_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (header_hbox, "header_hbox");
  gtk_widget_show (header_hbox);
  gtk_container_add (GTK_CONTAINER (header_frame), header_hbox);

  header_label = gtk_label_new (_("Tape"));
  gtk_widget_set_name (header_label, "header_label");
  gtk_widget_show (header_label);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_label, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (header_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (header_label), 6, 0);

  header_image = create_pixmap (tape_window, "window-tape.png");
  gtk_widget_set_name (header_image, "header_image");
  gtk_widget_show (header_image);
  gtk_box_pack_start (GTK_BOX (header_hbox), header_image, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (header_image), 4, 4);

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_box_pack_start (GTK_BOX (vbox), main_vbox, TRUE, TRUE, 0);

  file_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (file_hbox, "file_hbox");
  gtk_widget_show (file_hbox);
  gtk_box_pack_start (GTK_BOX (main_vbox), file_hbox, FALSE, TRUE, 0);

  file_comboboxentry = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (file_comboboxentry, "file_comboboxentry");
  gtk_widget_show (file_comboboxentry);
  gtk_box_pack_start (GTK_BOX (file_hbox), file_comboboxentry, TRUE, TRUE, 0);

  file_button_open = gtk_button_new ();
  gtk_widget_set_name (file_button_open, "file_button_open");
  gtk_widget_show (file_button_open);
  gtk_box_pack_start (GTK_BOX (file_hbox), file_button_open, FALSE, FALSE, 0);

  file_button_image_open = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (file_button_image_open, "file_button_image_open");
  gtk_widget_show (file_button_image_open);
  gtk_container_add (GTK_CONTAINER (file_button_open), file_button_image_open);

  file_button_close = gtk_button_new ();
  gtk_widget_set_name (file_button_close, "file_button_close");
  gtk_widget_show (file_button_close);
  gtk_box_pack_start (GTK_BOX (file_hbox), file_button_close, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (file_button_close, FALSE);

  file_button_image_close = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (file_button_image_close, "file_button_image_close");
  gtk_widget_show (file_button_image_close);
  gtk_container_add (GTK_CONTAINER (file_button_close), file_button_image_close);

  main_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (main_scrolledwindow, "main_scrolledwindow");
  gtk_widget_show (main_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_scrolledwindow, TRUE, TRUE, 0);
  gtk_widget_set_size_request (main_scrolledwindow, -1, 200);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_scrolledwindow), GTK_SHADOW_IN);

  main_treeview = gtk_tree_view_new ();
  gtk_widget_set_name (main_treeview, "main_treeview");
  gtk_widget_show (main_treeview);
  gtk_container_add (GTK_CONTAINER (main_scrolledwindow), main_treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (main_treeview), TRUE);

  progress_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (progress_hbox, "progress_hbox");
  gtk_widget_show (progress_hbox);
  gtk_box_pack_start (GTK_BOX (main_vbox), progress_hbox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (progress_hbox), 4);

  progress_led = gtk_drawing_area_new ();
  gtk_widget_set_name (progress_led, "progress_led");
  gtk_widget_show (progress_led);
  gtk_box_pack_start (GTK_BOX (progress_hbox), progress_led, FALSE, FALSE, 0);
  gtk_widget_set_size_request (progress_led, 20, 5);

  progress_hscale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 101, 0.1, 1, 1)));
  gtk_widget_set_name (progress_hscale, "progress_hscale");
  gtk_widget_show (progress_hscale);
  gtk_box_pack_start (GTK_BOX (progress_hbox), progress_hscale, TRUE, TRUE, 4);
  gtk_scale_set_draw_value (GTK_SCALE (progress_hscale), FALSE);

  control_hbox = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (control_hbox, "control_hbox");
  gtk_widget_show (control_hbox);
  gtk_box_pack_start (GTK_BOX (main_vbox), control_hbox, FALSE, TRUE, 0);

  control_button_play = gtk_toggle_button_new ();
  gtk_widget_set_name (control_button_play, "control_button_play");
  gtk_widget_show (control_button_play);
  gtk_box_pack_start (GTK_BOX (control_hbox), control_button_play, FALSE, TRUE, 0);
  gtk_button_set_relief (GTK_BUTTON (control_button_play), GTK_RELIEF_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (control_button_play), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = create_pixmap (tape_window, "media-play.png");
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic ("Play");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  control_button_previous = gtk_button_new ();
  gtk_widget_set_name (control_button_previous, "control_button_previous");
  gtk_widget_show (control_button_previous);
  gtk_box_pack_start (GTK_BOX (control_hbox), control_button_previous, FALSE, TRUE, 0);
  gtk_widget_set_sensitive (control_button_previous, FALSE);
  GTK_WIDGET_SET_FLAGS (control_button_previous, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (control_button_previous), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (control_button_previous), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = create_pixmap (tape_window, "media-start.png");
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic ("Previous");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  control_button_next = gtk_button_new ();
  gtk_widget_set_name (control_button_next, "control_button_next");
  gtk_widget_show (control_button_next);
  gtk_box_pack_start (GTK_BOX (control_hbox), control_button_next, FALSE, TRUE, 0);
  gtk_widget_set_sensitive (control_button_next, FALSE);
  GTK_WIDGET_SET_FLAGS (control_button_next, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (control_button_next), GTK_RELIEF_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (control_button_next), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = create_pixmap (tape_window, "media-end.png");
  gtk_widget_set_name (image3, "image3");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic ("Next");
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  control_button_stop = gtk_button_new ();
  gtk_widget_set_name (control_button_stop, "control_button_stop");
  gtk_widget_show (control_button_stop);
  gtk_box_pack_start (GTK_BOX (control_hbox), control_button_stop, FALSE, TRUE, 0);
  gtk_widget_set_sensitive (control_button_stop, FALSE);
  GTK_WIDGET_SET_FLAGS (control_button_stop, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (control_button_stop), GTK_RELIEF_NONE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (control_button_stop), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = create_pixmap (tape_window, "media-stop.png");
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic ("Stop");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  control_button_record = gtk_toggle_button_new ();
  gtk_widget_set_name (control_button_record, "control_button_record");
  gtk_widget_show (control_button_record);
  gtk_box_pack_start (GTK_BOX (control_hbox), control_button_record, FALSE, TRUE, 0);
  gtk_button_set_relief (GTK_BUTTON (control_button_record), GTK_RELIEF_NONE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (control_button_record), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = create_pixmap (tape_window, "media-record.png");
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic ("Record");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox), hseparator1, FALSE, FALSE, 4);

  dialog_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_set_name (dialog_hbuttonbox, "dialog_hbuttonbox");
  gtk_widget_show (dialog_hbuttonbox);
  gtk_box_pack_start (GTK_BOX (vbox), dialog_hbuttonbox, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_hbuttonbox), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (dialog_hbuttonbox), 6);

  dialog_button_help = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_set_name (dialog_button_help, "dialog_button_help");
  gtk_widget_show (dialog_button_help);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_help);
  GTK_WIDGET_SET_FLAGS (dialog_button_help, GTK_CAN_DEFAULT);

  dialog_button_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (dialog_button_close, "dialog_button_close");
  gtk_widget_show (dialog_button_close);
  gtk_container_add (GTK_CONTAINER (dialog_hbuttonbox), dialog_button_close);
  GTK_WIDGET_SET_FLAGS (dialog_button_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tape_window, tape_window, "tape_window");
  GLADE_HOOKUP_OBJECT (tape_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (tape_window, header_frame, "header_frame");
  GLADE_HOOKUP_OBJECT (tape_window, header_hbox, "header_hbox");
  GLADE_HOOKUP_OBJECT (tape_window, header_label, "header_label");
  GLADE_HOOKUP_OBJECT (tape_window, header_image, "header_image");
  GLADE_HOOKUP_OBJECT (tape_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (tape_window, file_hbox, "file_hbox");
  GLADE_HOOKUP_OBJECT (tape_window, file_comboboxentry, "file_comboboxentry");
  GLADE_HOOKUP_OBJECT (tape_window, file_button_open, "file_button_open");
  GLADE_HOOKUP_OBJECT (tape_window, file_button_image_open, "file_button_image_open");
  GLADE_HOOKUP_OBJECT (tape_window, file_button_close, "file_button_close");
  GLADE_HOOKUP_OBJECT (tape_window, file_button_image_close, "file_button_image_close");
  GLADE_HOOKUP_OBJECT (tape_window, main_scrolledwindow, "main_scrolledwindow");
  GLADE_HOOKUP_OBJECT (tape_window, main_treeview, "main_treeview");
  GLADE_HOOKUP_OBJECT (tape_window, progress_hbox, "progress_hbox");
  GLADE_HOOKUP_OBJECT (tape_window, progress_led, "progress_led");
  GLADE_HOOKUP_OBJECT (tape_window, progress_hscale, "progress_hscale");
  GLADE_HOOKUP_OBJECT (tape_window, control_hbox, "control_hbox");
  GLADE_HOOKUP_OBJECT (tape_window, control_button_play, "control_button_play");
  GLADE_HOOKUP_OBJECT (tape_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (tape_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (tape_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (tape_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (tape_window, control_button_previous, "control_button_previous");
  GLADE_HOOKUP_OBJECT (tape_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (tape_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (tape_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (tape_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (tape_window, control_button_next, "control_button_next");
  GLADE_HOOKUP_OBJECT (tape_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (tape_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (tape_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (tape_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (tape_window, control_button_stop, "control_button_stop");
  GLADE_HOOKUP_OBJECT (tape_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (tape_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (tape_window, image4, "image4");
  GLADE_HOOKUP_OBJECT (tape_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (tape_window, control_button_record, "control_button_record");
  GLADE_HOOKUP_OBJECT (tape_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (tape_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (tape_window, image5, "image5");
  GLADE_HOOKUP_OBJECT (tape_window, label5, "label5");
  GLADE_HOOKUP_OBJECT (tape_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (tape_window, dialog_hbuttonbox, "dialog_hbuttonbox");
  GLADE_HOOKUP_OBJECT (tape_window, dialog_button_help, "dialog_button_help");
  GLADE_HOOKUP_OBJECT (tape_window, dialog_button_close, "dialog_button_close");

  return tape_window;
}

