.TH tdtodump 1

.SH NAME
tdtodump \- convert TeleDisk images to disk dump files

.SH SYNOPSIS
.B tdtodump <infile> <outfile>
.br

.SH DESCRIPTION
.B tdtodump
converts disk images produced by the Sydex TeleDisk program
to uncompressed disk dumps. The format of the disk dumps is
compatible with the file format used by the Sydex AnaDisk
program.
.LP

.SH BUGS
Currently only images created with normal compression are
supported.

.SH SEE ALSO
kcemu(1x)

.SH AUTHOR
This manual page was written by Torsten Paul <Torsten.Paul@gmx.de>,
for the Debian GNU/Linux system (but may be used by others).
